Add //os.tree to return a directory/file tree
arr-ai/arrai pull request #606
Opened 2020-08-27 08:36 UTC by orlade-anz

Fixes #605 .

Changes proposed in this pull request:
- Add `//os.tree` that returns a dictionary representing the file system.
- Directory names are keys mapping to dictionaries.
- Filenames are keys mapping to `true`.

Checklist:
- [ ] Added related tests
- [ ] Made corresponding changes to the documentation

2020-08-28 04:02 UTC, nofun97 requested changes
also add documentation in here https://github.com/arr-ai/arrai/blob/master/docs/std-os.md

2020-08-28 04:02 UTC, nofun97 commented on syntax/std_os_nonwasm.go
> +			rel.NewBoolAttr("isDir", info.IsDir()),
```suggestion
			rel.NewBoolAttr("is_dir", info.IsDir()),
```

2020-08-28 04:02 UTC, nofun97 commented on syntax/std_os_nonwasm.go
> +			rel.NewFloatAttr("modTime", float64(info.ModTime().UnixNano())),
for consistency with other stdlib functions
```suggestion
			rel.NewFloatAttr("mod_time", float64(info.ModTime().UnixNano())),
```

2020-08-31 04:09 UTC, orlade-anz commented
Docs already done?

2020-10-01 01:35 UTC, merged