Bundle
arr-ai/arrai pull request #621
Opened 2020-09-02 05:34 UTC by nofun97

Part of #584 

Changes proposed in this pull request:
- adds `arrai bundle` command that bundles all dependencies into a runnable format

Checklist:
- [ ] Added related tests
- [ ] Made corresponding changes to the documentation

2020-09-02 07:44 UTC, orlade-anz reviewed
Nice 👍

2020-09-02 07:44 UTC, orlade-anz commented on cmd/arrai/bundle.go
> +	Usage:   "bundle arrai script and its dependencies into a runnable file. It outputs .arraiz file.",
Nit: 
```suggestion
	Usage:   "bundles an arr.ai script and its imports into an .arraiz file that can be `arrai run`.",
```

2020-09-02 08:29 UTC, marcelocantos approved these changes
Great work!

2020-09-04 01:03 UTC, orlade-anz requested changes

2020-09-04 01:06 UTC, orlade-anz commented
I don't understand most of this but it looks good!

2020-09-04 01:08 UTC, nofun97 commented
> I don't understand most of this but it looks good!
I should probably add a documentation then. Will add a design doc.

2020-09-04 01:11 UTC, orlade-anz commented
> I should probably add a documentation then. Will add a design doc.

I applaud your enthusiasm, and it would be nice, but don't invest too much in it since this is a somewhat temporary solution.

2020-09-04 01:24 UTC, orlade-anz approved these changes

2020-09-04 06:09 UTC, merged